version: "3.8"

services:
  postgres:
    image: "bitnami/postgresql"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=app
    volumes:
      - "postgresql_data:/bitnami/postgresql"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
